/**
 * Bundles the player runtime — src/player/runtime.ts plus the engine it
 * reuses — into one minified IIFE at src/player/runtime.generated.js.
 * That file is committed: exportPlayable inlines it into every playable
 * HTML file, and the player tests boot it. Rerun after touching the
 * runtime or the engine:  pnpm build:runtime
 */
import { build } from 'esbuild'

await build({
  entryPoints: ['src/player/runtime.ts'],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2020',
  outfile: 'src/player/runtime.generated.js',
  banner: { js: '/* Generated by scripts/build-runtime.mjs — do not edit. Rebuild: pnpm build:runtime */' },
  logLevel: 'warning',
})
console.log('runtime.generated.js written')
